apiVersion: apps/v1          # Version of the API to use.
kind: Deployment             # "top-level" API type.
metadata:
  labels:
    app: nginx               # Tag deployment with app label
  name: nginx-deployment     # Unique name of deployment object within namespace.
  namespace: nginx-demo      # Unique name of namespace of deployment object.
spec:                        # Desired state of deployment.
  replicas: 1                # Number of desired pods.
  selector:                  # Label selector for pods.
    matchLabels:             # Existing ReplicaSets whose pods are selected by this will be the ones affected by this deployment.
      app: nginx             # It must match the pod template's labels.
  template:                  # Template describes the pods that will be created.
    metadata:
      annotations:
        imageregistry: "https://hub.docker.com/"
      labels:
        app: nginx           # Selector label
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "2Gi"
              cpu: "1000m"
            requests:
              memory: "1Gi"
              cpu: "500m"