apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx-node-port
  namespace: nginx-demo
spec:
  ports:              # Lists of named subobjects preferred over maps
    - nodePort: 30000 # externally exposed port e.g. localhost:30080
      port: 80        # static node port (virtual or physical machine) e.g. docker-desktop
      protocol: TCP
      targetPort: 80  # container port e.g. deployment/nginx
  selector:
    app: nginx
  type: NodePort
