#!/bin/sh
IMAGE_NAME_VERSION="nginx:latest"
echo $IMAGE_NAME_VERSION
GITHUB_MLIBRARY_GITHUB_USER_IMAGE_NAME_VERSION="ghcr.io/mlibrary/${GITHUB_USER}/${IMAGE_NAME_VERSION}"
echo $GITHUB_MLIBRARY_GITHUB_USER_IMAGE_NAME_VERSION
docker tag $IMAGE_NAME_VERSION $GITHUB_MLIBRARY_GITHUB_USER_IMAGE_NAME_VERSION
docker login ghcr.io --username $GITHUB_USER --password $GITHUB_WRITE_PACKAGES_TOKEN
docker push $GITHUB_MLIBRARY_GITHUB_USER_IMAGE_NAME_VERSION