apiVersion: v1
kind: Service
metadata:
  labels:
    app: fulcimen
  name: fulcimen-node-port
  namespace: fulcimen-demo
spec:
  ports:
    - nodePort: 30000 # externally exposed port e.g. localhost:30080
      port: 3000      # static node port (virtual or physical machine) e.g. docker-desktop
      protocol: TCP
      targetPort: 3000  # container port e.g. deployment/fulcimen
  selector:
    app: fulcimen
  type: NodePort