apiVersion: v1
kind: Service
metadata:
  labels:
    app: fulcimen
  name: mysql
  namespace: fulcimen-demo
spec:
  type: ExternalName
  externalName: host.docker.internal
# Commented out line 4 and added line 5 to /usr/local/etc/my.cnf
#  1 # Default Homebrew MySQL server config
#  2 [mysqld]
#  3 # Only allow connections from localhost
#  4 # bind-address = 127.0.0.1
#  5 bind-address = 0.0.0.0
# So MySQL will accept external connections