apiVersion: v1
kind: Pod
metadata:
  labels:
    app: fulcimen
  name: mysql-client
  namespace: fulcimen-demo
spec:
  containers:
    - image: alpine
      name: alpine
      command: ["sh"]
      args: ["-c", "sleep 100000"]
# Sleep long enough to use for host MySQL connection testing
#   kubectl -c alpine -it exec mysql-client --namespace=fulcimen-demo -- sh
# Use ping to test connection to host
#   ping mysql
# Install mysql-client to test connection to host MySQL
#   apk --no-cache add mysql-client
#   mysql -h mysql -u root
#   Welcome to the MariaDB monitor.  Commands end with ; or \g.
#   Your MySQL connection id is 19
#   Server version: 8.0.23 Homebrew
#
#   Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.
#
#   Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
#   MySQL [(none)]> show databases;
#   +--------------------------------+
#   | Database                       |
#   +--------------------------------+
#   | gkostin_heliotrope_development |
#   | gkostin_heliotrope_test        |
#   | heliotrope_development         |
#   | heliotrope_test                |
#   | heliotropium_development       |
#   | heliotropium_test              |
#   | information_schema             |
#   | mysql                          |
#   | performance_schema             |
#   | swapmeet_development           |
#   | swapmeet_test                  |
#   | sys                            |
#   | thyrax_development             |
#   | thyrax_test                    |
#   +--------------------------------+
#   14 rows in set (0.004 sec)
#
#   MySQL [(none)]> quit
#   Bye
#   exit