name: testing-deploy-fulcimen-mysql

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: fulcrum-testing
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Kubectl
        uses: azure/setup-kubectl@v1
      - name: Authenticate with kubernetes cluster
        run: |
          mkdir -p ${HOME}/.kube/certs/cluster
          echo ${{ secrets.CA_CRT_BASE64 }} | base64 -d > ${HOME}/.kube/certs/cluster/k8s-ca.crt
          kubectl config set-cluster cluster --certificate-authority=${HOME}/.kube/certs/cluster/k8s-ca.crt --server=`echo ${{ secrets.SERVER_URL_BASE64 }} | base64 -d`
          kubectl config set-credentials default --token=`echo ${{ secrets.TOKEN_BASE64 }} | base64 -d`
          kubectl config set-context default --cluster=cluster --user=default --namespace=`echo ${{ secrets.NAMESPACE_BASE64 }} | base64 -d`
          kubectl config use-context default
          kubectl config view
          kubectl config current-context
      - name: Deploy with kubectl apply
        run: |
          kubectl apply -f ./.github/manifests/fulcimen-mysql-deployment.yaml